### PR TITLE
feat: Creating and Editing Donation Backend Integration, Thank You Screen

### PR DESCRIPTION
**Pull request by Shehryar21**
## Notion ticket link

[Scheduling Backend Integration](https://www.notion.so/uwblueprintexecs/Scheduling-Backend-Integration-c2b917c67c2144bda5415faccebee84b)
[Changes for scheduling screens when being edited](https://www.notion.so/uwblueprintexecs/Changes-for-scheduling-screens-when-being-edited-313595846ac84f3992b56ee2e57de48d)

## Implementation description
* Backend Integration for creating and editing a donation
* Changed some Types stuff. We had two types for the same scheduling data, so I made that into one and had to make few changes cuz of that.
* Thank You Screen - Made that part of the scheduling flow steps instead of being on a different route since for start time we need to access formvalues
* Backend Table change. Made isPickup not mandatory since if u dont require a volunteer, isPickup will be null
* Changes to other Scheduling screens for editing donation
* Also changed the get started image from svg to png. For some reason svg took so long to load and browser was getting stuck. Changing to png worked fine

## Steps to test
1. Recreate Backend DB: Remove existing tables and recreate them and then do `node seed up`
2. Create a donation following the scheduling steps. Make sure to add valid input. For example for recurring end date input has to be in MM/DD/YYYY so please add it like this since we dont have Frontend validations yet and this will cause errors adding to backend
3. Check if it added in the donor Dashboard
4. Try editing the donation

## What should reviewers focus on?
* Make sure i didnt break anything and you can create and edit donation properly

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by hanlinc27 — APPROVED** [review]

**Review by annechung — COMMENTED** [review]
tested locally and it works well! is it possible to get better resolution pictures for the get started/thank you pages?

**Comment by Shehryar21** [comment]
> tested locally and it works well! is it possible to get better resolution pictures for the get started/thank you pages?

For getting started, we were using svg but it took so long to load and browser was not responding which is why I changed to png. I downloaded straight from Figma tho.

**Comment by annechung** [comment]
> > tested locally and it works well! is it possible to get better resolution pictures for the get started/thank you pages?
> 
> For getting started, we were using svg but it took so long to load and browser was not responding which is why I changed to png. I downloaded straight from Figma tho.

Ah yeah exporting from figma drops the quality by a lot, we should ask the designers to send the images to us directly. we can switch those out after this is merged though

**Comment by AmandaMisjuwar** [comment]
> > tested locally and it works well! is it possible to get better resolution pictures for the get started/thank you pages?
> 
> For getting started, we were using svg but it took so long to load and browser was not responding which is why I changed to png. I downloaded straight from Figma tho.

BTW not sure if you downloaded it as 4x, the image quality would look better if you haven't already! @Shehryar21

**Pull request merged**
